version: '3'

services:
  web:
    build: .
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK-APP: app.py
      FLASK_ENV: development
    command: "flask run"

  redis:
    image: "redis:alpine"
